apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerdemo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockerdemo-api
  template:
    metadata:
      labels:
        app: dockerdemo-api
    spec:
      containers:
      - name: dockerdemo-api
        image: place_holder
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: AzureAd__TenantId
          value: "8b429d1a-74b0-4d77-8bc0-46497daeee71"
        - name: AzureAd__ClientId
          value: "e1709cbf-5ac7-45dd-b932-736744fcb4d0"
        - name: AzureAd__Instance
          value: "https://login.microsoftonline.com/"
        # - name: ConnectionStrings__DefaultConnection
        #   value: "${DB_CONNECTIONSTRING}"      
---
apiVersion: v1
kind: Service
metadata:
  name: dockerdemo-service
spec:
  type: LoadBalancer
  selector:
    app: dockerdemo-api
  ports:
    - port: 80
      targetPort: 8080